# Generated by Django 5.1.3 on 2025-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offer_user_offer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
